on:
  pull_request:
  
jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/delete-package-versions@v4
            with:
              package-name: ghcr.io/center-for-threat-informed-defense/center-for-threat-informed-defense/attack-workbench-collection-manager
              package-type: container
              num-old-versions-to-delete: 100
              min-versions-to-keep: 0


    