name: Retroactively publish Docker image for tagged releases

on:
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Check branch name
        run: |
            BRANCH_NAME=${GITHUB_HEAD_REF#refs/heads/}
            if [[ ! $BRANCH_NAME == *-retroactively-publish-docker-image-for-all-tagged-releases ]]; then
            echo "Branch name does not match the pattern. Skipping the workflow."
            exit 1
            fi
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Check if Dockerfile exists
        id: dockerfile
        run: |
          if [ ! -f Dockerfile ]; then
            echo "No Dockerfile in this commit. Skipping this workflow run."
            exit 1
          fi
      -
        name: Get list of tags
        id: get_tags
        run: |
          TAGS=$(git tag --contains HEAD)
          echo "::set-output name=tags::$TAGS"
      -
        name: Validate git tag version and Build Image
        run: |
          for TAG in ${{ steps.get_tags.outputs.tags }}
          do
            VERSION=$(echo $TAG | cut -d / -f 3)
            if [[ $VERSION =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              echo "Building and Pushing Docker Image for Tag: $VERSION"
              echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
              IMAGE_NAME="ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:$VERSION"
              docker build -t $IMAGE_NAME .
              docker push $IMAGE_NAME
            else
              echo "Skipping Tag: $VERSION as it is not semver compliant"
            fi
          done
